### ISSUE TITLE
[Spike] 재수생을 고려한 데이터 모델링

### ISSUE THREAD

**Issue by DaleSeo** [DaleStudy/leaderboard#100]
[디스코드 쓰레드](https://discord.com/channels/775115965964222492/1311508728821846057) 에서 논의했던 것처럼 데이터 모델링할 때 재수생에 대한 고려가 부족했던 것 같습니다.

본 티켓을 통해서 재수생을 어떻게 처리하는 것이 가장 합리적일지 판단하고, 그에 따른 데이터 모델링 수정 사항을 탐구해주세요.

일단 제가 합리적이라고 생각하는 방향으로 요구 사항을 두서 없이 적어봤는데 다른 의견이 있으면 피드백 부탁드립니다.

- 재수생은 여러 차수(cohort)에 속할 수 있어야 한다.
   - 예를 들어, 1기에 참여하고 3기에 참여한 멤버가 있다면...
   - 이 멤버는 GitHub에서 leetcode01 팀에도 속하고, leetcode03 팀에도 속한다.
   - 따라서, 리더보드에서 필터에서 1기를 선택했을 때도 나오고 3기를 선택했을 때도 나와야 한다.
   - 하지만, 전체 기수를 선택했을 때는 한 번만 나와야 한다.
- 하나의 문제에 대해서 여러 언어로 (즉, 여러 확장자 / 예, yolophg.py, yolophg.js) 답안 코드가 제출이 되었을 때, 하나의 제출로 처리가 되야한다.
  - 40문제를 두 개의 언어로 풀면 80 제출로 만랩이 되는데, 75문제를 모두 푸는 것을 목표로 하는 스터디의 취지와 맞지 않다.
  - 만약에 만년 재수생이 생긴다면 자연스럽게 만랩이 될 수 있다.
- 하나의 문제에 대해서 같은 언어로 여러 답안 코드가 제출이 되었을 때 (예, yolophg.py, yolophg2.js) 답안 코드가 제출이 되었을 때, 하나의 제출로 처리가 되야한다.
  - 근거는 바로 위 요구사항과 동일

**Comment by sounmind** [comment]
전체 기수를 선택했을 때 나오는 재수생의 Grade와 Progress는 어떤 기수를 기준으로 나와야 할까요?

**Comment by DaleSeo** [comment]
> 전체 기수를 선택했을 때 나오는 재수생의 Grade와 Progress는 어떤 기수를 기준으로 나와야 할까요?

Grade와 Progress 기수와 무방하게 통합되서 산출되야 할 것 같은데요? 위에 명시한 요구 사항데로 여러 언어와 여러 답안이 하나의 제출로 처리된다면 가능하지 않을까요?

**Comment by HC-kang** [comment]
>하나의 문제에 대해서 여러 언어로 (즉, 여러 확장자 / 예, yolophg.py, yolophg.js) 답안 코드가 제출이 되었을 때, 하나의 제출로 처리가 되야한다.

이 부분은 디스코드에서 말씀드렸다시피, 현행과 같고, 문제가 되진 않습니다.

>Grade와 Progress 기수와 무방하게 통합되서 산출되야 할 것 같은데요? 위에 명시한 요구 사항데로 한 멤버가 제출한 여러 언어와 여러 답안이 하나의 제출로 처리된다면 가능하지 않을까요?

위 조건에 따라 이 부분도 현재로서는 문제가 되지 않습니다.

약간의 용어 정리가 필요해보이는데, 이렇게 정리하면 어떨까 싶습니다.

하나의 문제에 대해서 여러 언어로 답안 코드가 제출이 되었을 때, 하나의 **제출**로 처리가 되야한다. (`submission`)
=> 하나의 문제에 대해서 여러 언어로 답안 코드가 제출이 되었을 때, 하나의 **완료**로 처리가 되야한다. (`completion`)

40문제에 대해 80개의 답안을 제출(`submission`)했더라도, 완료(`completion`)는 40개로 중복이 제거된 실제 75문제에 대한 진척률을 나타낼 수 있어보입니다.

현 상황에서 문제 해결을 위해 강구해야 하는 요건은, **각각의 제출이 몇기 때 제출된것인지**만 알 수 있으면 될 것으로 보입니다

위 조건만 해결되면 아래와 같은 표현이 충분히 가능합니다.

- 1기에서 30문제를  풀었다면
  - 1기 30문제 제출
  - 1기 30문제 완료
  - 1기 진척률 40%

- 2기에서 30문제를 풀었다면(기존과 중복된 것 15건, 새로운 문제 15건)
  - 2기 30문제 제출
  - 2기 30문제 완료
  - 2기 진척률 40%
  - 누적 45문제 완료
  - 누적 진척률 60%

- 3기에서 30문제를 출었다면(새로운 문제 30건)
  - 3기 30문제 제출
  - 3기 30문제 완료
  - 3기 진척률 40%
  - 누적 75문제 완료
  - 누적 진척률 100%

**Comment by DaleSeo** [comment]
@HC-kang 님, 의견 감사합니다.

여러 개의 제출이 하나의 완료로 처리되야 한다는 부분에 동의합니다.

진척률에 대해서는 기수와 상관없이 개인별 누적 진척률만 산출하면 어떨까요?
진척률이 등급을 결정하고 곧 수료증 발급 여부에 영향을 주기 때문입니다.

**Comment by DaleSeo** [comment]
@HC-kang 님, 추가로 질문이 있는데요. 아래 속성이 `cohorts`로 바뀌고 배열이 저장되야 할 것 같은데 어떻게 생각하세요?

https://github.com/DaleStudy/leaderboard/blob/355629210bd06aa0d2b97508c37a6d157f2879de/src/api/services/types.ts#L36

**Comment by DaleSeo** [comment]
@HC-kang 네, 현재 데이터 모델링은 member랑 cohort가 1:m 관계인데, m:n 관계로 변경이 되야 재수생을 제대로 표현할 수 있을 것 같습니다.

**Comment by DaleSeo** [comment]
데이터 모델링을 어떻게 변경할지 어느정도 감이 잡힌 것 같은데 구현 티켓 생성하고 @HC-kang 님께 할당해드렸습니다!
https://github.com/DaleStudy/leaderboard/issues/114

혹시 추가로 논의할 부분이 있으시면 알려주세요 😸
