### ISSUE TITLE
컴포넌트 색깔 관련 접근성 이슈

### ISSUE THREAD

**Issue by SamTheKorean** [DaleStudy/leaderboard#112]
Table, Button, Sidebar, Card 컴포넌트에서 배경과 컴포넌트의 생상 등등 색깔 차이가 일정 기준을 충족하지 못해 접근성 violation 문제가 발생하고 있습니다. 

이 부분은 @yolophg 님이 추후에 chromatics에서 확인 부탁드리겠습니다!

관련 맥락은 링크를 통해 남겨두었습니다.
https://github.com/DaleStudy/leaderboard/pull/81#issuecomment-2510261338

**Comment by DaleSeo** [comment]
@SamTheKorean 님, 담부터 이슈 생성해주실 때는 꼭 프로젝트에 연결해주시길 부탁드립니다. 요 이슈를 한참 찾았네요 ㅋㅋ 🤣

**Comment by yolophg** [comment]
해당 violation 이슈 있던 컴포넌트인 primary, secondary 버튼 제 로컬에서 테스트 후에 에러 없는 부분 확인하고 최종적으로 아래와 같이 피그마에 업데이트 되었습니다.
전반적으로 primary->bg-400 컬러로 변경되었다고 보시면 되고 추가적으로, primary의 경우 hover시에 bg-300과 text-900을 사용하는 것으로 변경되었습니다.
tertiary 컬러도 필요가 없어져서 제거하였고 같이 업데이트 해두었으니 자세한 사항은 피그마를 확인해주시고 업데이트 해주시면 감사드리겠습니다 :).<img width="423" alt="Image" src="https://github.com/user-attachments/assets/1de2f552-3787-45e4-a39c-7317c3d277c9" />
<img width="379" alt="Image" src="https://github.com/user-attachments/assets/d0437e29-795e-48cc-8762-deb1ee12a052" />
<img width="218" alt="Image" src="https://github.com/user-attachments/assets/b10e8f96-32fb-48bd-bc00-549e78a5a9e3" />

**Comment by DaleSeo** [comment]
@yolophg 수고하셨습니다!

변경된 디자인을 반영하기 위한 구현 티켓을 생성하였습니다 #148
