### ISSUE TITLE
멤버 카드가 홀수 일 때 너비 이슈

### ISSUE THREAD

**Issue by DaleSeo** [DaleStudy/leaderboard#118]
리더보드에서 홀수의 멤버가 있을 때 마지막 멤버 카드의 너비가 다른 카드의 너비 2배가 됩니다.

![Image](https://github.com/user-attachments/assets/5601630c-2105-4676-8d0f-8dd1df0aa408)

**Comment by DaleSeo** [comment]
@yolophg 버그로 봐도 될지 컨펌 부탁드립니다.

**Comment by yolophg** [comment]
> @yolophg 버그로 봐도 될지 컨펌 부탁드립니다.

버그 맞습니다. 디자인 가이드라인 참고하시면, 각 카드가 동일한 너비(50%)를 유지하며 그리드 레이아웃에서 균등하게 분배되어야 합니다.
아래 부분 참고해서 수정 부탁드립니다. 일단, Card Component 작업해주신 @Sunjae95 님 멘션드립니다!
<img width="424" alt="Screenshot 2024-12-07 at 17 19 20" src="https://github.com/user-attachments/assets/2b0d602c-6603-45cd-84c9-1fad10d4a8d7">

**Comment by Sunjae95** [comment]
그러네요! 해당 이슈에서 브랜치 만들어서 수정할게요~
