### ISSUE TITLE
프로젝트 초기 셋업

### ISSUE THREAD

**Issue by DaleSeo** [DaleStudy/leaderboard#12]
- Based on https://github.com/DaleStudy/leaderboard/issues/9
- 폴더 구조

**Comment by DaleSeo** [comment]
@sounmind 생각해보니 Octokit은 굳이 처음부터 설치할 필요는 없을 것 같아요. 기껏해야 3개 정도 API를 호출할 거니까 배보다 배꼽이 더 클 수 있을 것 같습니다. 나중에 구현하면서 필요성이 느껴지면 설치하시죠.

**Comment by DaleSeo** [comment]
@sounmind 생각해보니 약간의 라우팅도 필요하겠네요? React Router도 설치하고 기본 셋업을 하면 좋을 것 같네요?

- https://leaderboard.dalestudy.com/ : 리더보드 페이지
- https://leaderboard.dalestudy.com/progress: 프로그레스 페이지
- https://leaderboard.dalestudy.com/certificate: 수료증 페이지

**Comment by sounmind** [comment]
@DaleSeo 

> [@sounmind](https://github.com/sounmind) 생각해보니 Octokit은 굳이 처음부터 설치할 필요는 없을 것 같아요. 기껏해야 3개 정도 API를 호출할 거니까 배보다 배꼽이 더 클 수 있을 것 같습니다. 나중에 구현하면서 필요성이 느껴지면 설치하시죠.

네. 동의합니다!

---

> [@sounmind](https://github.com/sounmind) 생각해보니 라우팅을 위해서 React Router와 같은 의존성도 필요하겠네요?

맞아요. 더 나은 대안이 없어보여서 [React Router](https://reactrouter.com/en/main) 그대로 사용해보도록 하겠습니다.

**Comment by sounmind** [comment]
- [x] TypeScript
- [x] React
- [x] Vite
- [x] Vitest
- [x] Testing Library
- [x] Storybook
- [x] Prettier/ESLint
- [x] Bun
- [ ] React Router
- [ ] CSS-in-JS (PandaCSS)
- [ ] TanStack Query

**Comment by DaleSeo** [comment]
> 맞아요. 더 나은 대안이 없어보여서 [React Router](https://reactrouter.com/en/main) 그대로 사용해보도록 하겠습니다.

TanStack Query를 쓸 거라면 TanStack Router가 더 궁합이 좋을 수 있을 것 같습니다!: https://tanstack.com/router/latest

**Comment by sounmind** [comment]
> TanStack Query를 쓸 거라면 TanStack Router가 더 궁합이 좋을 수 있을 것 같습니다!: https://tanstack.com/router/latest (비교표: https://tanstack.com/router/latest/docs/framework/react/comparison)

어떤 것을 사용하건 그만의 장단점이 있을 것 같네요. 하지만 현재 저희 프로젝트 요구사항에 TanStack Query와 TanStack Router의 궁합이 시너지를 발휘할 거라고는 생각하기 어려워요. 그런데 기존 요구사항에 부합하고 익숙하다고 생각했던 React Router의 최신 명세는 이전과는 많이 달라져서 TanStack Query를 사용하나 React Router를 사용하나 둘 다 낯설 수 있겠다고 생각했습니다.

저는 개인적으로 현 프로젝트에는 React Router로 충분하고 앞으로도 그럴 것 같다는 생각이 드는데요. TanStack Router도 충분히 배우고 사용할만한 가치가 있어 보입니다. 하지만 제가 아직 TanStack Router 관련 경험이 실제 프로젝트 없어서 확신이 없네요!

선택하기가 어렵네요... 최종 결정은 @DaleSeo 님이 해주셨으면 좋겠습니다~
