### ISSUE TITLE
Error 500 Component

### ISSUE THREAD

**Issue by sounmind** [DaleStudy/leaderboard#124]
[Spec](https://github.com/DaleStudy/leaderboard/issues/124#issuecomment-2536193751)

**Comment by sounmind** [comment]
@DaleStudy/leaderboard 
<img width="352" alt="image" src="https://github.com/user-attachments/assets/5ac32056-2bf4-4690-8483-8461b36c5047">

위 디자인 컴포넌트를 참고했을 때 해당 티켓은 일반적인 500 에러(배포 서버, Github 장애 등 예측하지 못한 에러)에 대한 UI 라기 보다는 저희 API 호출 중 에러가 발생했을 때 보여주는 에러라고 판단했는데 맞을까요?

**Comment by sounmind** [comment]
@DaleStudy/leaderboard Progress 페이지에서 잘못된 query param으로 진입했을 경우 어떤 에러로 취급해야 할지 궁금합니다.
- 404?
- API 에러(현재 500 에러 컴포넌트)? (실제로 모든 멤버를 찾는 API 요청은 성공해서 이 에러는 아닐 것 같습니다.
- 아니면 커스텀 에러(멤버를 찾을 수 없습니다)...? (이를 위해서는 새로운 UI가 필요할 수도 있습니다)

**Comment by DaleSeo** [comment]
@sounmind 질문에 의견드립니다.

> 위 디자인 컴포넌트를 참고했을 때 해당 티켓은 일반적인 500 에러(배포 서버, Github 장애 등 예측하지 못한 에러)에 대한 UI 라기 보다는 데이터를 불러오기 위한 API 호출 중 에러가 발생했을 때 보여주는 UI 컴포넌트라고 판단했는데 맞을까요?

네, 저는 그렇게 생각하고 있었습니다. 서버 사이드 코드가 없으니까요.

> Progress 페이지에서 잘못된 query param으로 진입했을 경우 어떤 에러로 취급해야 할지 궁금합니다.

"잘못된 query param"이 정확히 어떤 경우를 의미하시는 걸까요? 지원하지 않는 키가 명시되었을 때? 아니면 값에 문제가 있는 경우? 예를 들어서 설명해주시면 좀 더 이해가 쉬울 것 같습니다.

**Comment by sounmind** [comment]
> "잘못된 query param"이 정확히 어떤 경우를 의미하시는 걸까요? 지원하지 않는 키가 명시되었을 때? 아니면 값에 문제가 있는 경우? 예를 들어서 설명해주시면 좀 더 이해가 쉬울 것 같습니다.

맞습니다!

- 존재하지 않는 member id로 진입했을 때(예: `/progress?member=unknown-user-id`)
- 지원하지 않는 query param으로 진입했을 때(예: `/progress?unknown-query-param=sounmind`)

등에 대한 에러는 어떻게 대응해야 할지? 궁금했습니다. 이는 서버 에러라기 보다 유저가 잘못 진입한 400대의 에러라고 생각합니다. 이를 위한 UI가 별도로 있으면 좀 더 친절한 웹사이트가 되리라 생각하는데요. 어떻게 생각하시나요?

**Comment by Sunjae95** [comment]
@sounmind 님이 고려하시는부분은 제가 잠깐 적어봤어요.

존재하지 않는 member id로 진입했을 때(예: /progress?member=unknown-user-id)
대응: https://github.com/DaleStudy/leaderboard/pull/117 조회할수없기에 404라고 생각하고 작업

지원하지 않는 query param으로 진입했을 때(예: /progress?unknown-query-param=sounmind)
대응: 각 페이지에서 querystring의 정해진 key값으로 조회하므로 고려할 필요가 없다고 판단

> 위 디자인 컴포넌트를 참고했을 때 해당 티켓은 일반적인 500 에러(배포 서버, Github 장애 등 예측하지 못한 에러)에 대한 UI 라기 보다는 데이터를 불러오기 위한 API 호출 중 에러가 발생했을 때 보여주는 UI 컴포넌트라고 판단했는데 맞을까요?

저도 github api 장애로 인한 에러페이지라고 생각하고 있어요. 그러면 useMember의 error값으로 404, 500에 대한 분기처리로직이 필요할거 같아요.

**Comment by yolophg** [comment]
> > "잘못된 query param"이 정확히 어떤 경우를 의미하시는 걸까요? 지원하지 않는 키가 명시되었을 때? 아니면 값에 문제가 있는 경우? 예를 들어서 설명해주시면 좀 더 이해가 쉬울 것 같습니다.
> 
> 맞습니다!
> 
> * 존재하지 않는 member id로 진입했을 때(예: `/progress?member=unknown-user-id`)
> * 지원하지 않는 query param으로 진입했을 때(예: `/progress?unknown-query-param=sounmind`)
> 
> 등에 대한 에러는 어떻게 대응해야 할지? 궁금했습니다. 이는 서버 에러라기 보다 유저가 잘못 진입한 400대의 에러라고 생각합니다. 이를 위한 UI가 별도로 있으면 좀 더 친절한 웹사이트가 되리라 생각하는데요. 어떻게 생각하시나요?
> 
> + 추가) "존재하지 않는 member id로 진입했을 때(예: `/progress?member=unknown-user-id`)"는 @Sunjae95 님이 #117 에서 커버하고 있는 것 같습니다.

이 부분 피그마에도 답변 드렸는데, 두 케이스 모두 말씀하신대로 Page Not Found(404)로 처리가 될거라 예상하고 해당 UI를 구현해두었으니, 참고 부탁드립니다!
[Error Page 관련 issue 링크](https://github.com/DaleStudy/leaderboard/issues/61)

**Comment by sounmind** [comment]
## Specification
- API 에러 시 보여주는 UI
- [ ] Leaderboard Page에서 Error UI
- Progress Page
  - [ ] Sidebar Error UI (테이블 헤더는 보이면서 Error UI를 안에 들어가야 함)
  - [ ] Table Error UI

피그마와 이슈에서 논의한 것들 참고해서 이렇게 스펙으로 삼겠습니다.
모두 답변 감사합니다~ㅎㅎ
