### ISSUE TITLE
Sprint 11 미팅

### ISSUE THREAD

**Issue by DaleSeo** [DaleStudy/leaderboard#128]
## Progress
- 제품 시연
- 지난 Sprint 리뷰
- 다음 Sprint 계획

## Agenda
- 스토리북을 테스팅 도구로 활용하기 (Interactions 탭)

## Action Items
-

## Retro
https://github.com/DaleStudy/leaderboard/discussions/93

**Comment by Sunjae95** [comment]
### 대화내용
티켓은 depth가 존재하지 않는 flat구조로 생성할 것
- 팀 규모나 깃허브 기능이 제한적 이슈
동시에 작업하는 티켓은  2개를 초과하지말자
- 팀원에게 리뷰적으로 부담을 줄 수 있음
