### ISSUE TITLE
[Spike] 페이지네이션 전략

### ISSUE THREAD

**Issue by sounmind** [DaleStudy/leaderboard#136]
페이지네이션 전략으로 크게 아래 3가지를 조사했습니다.

1. 오프셋 기반 페이지네이션  
2. 커서 기반 페이지네이션  
3. 무한 스크롤/더 보기 버튼  

각각의 특징과 장단점을 살펴보아요.

---

### 1. 오프셋 기반 페이지네이션
- **특징**:  
  - `page=2&limit=10`과 같이 현재 페이지와 페이지당 보여줄 개수를 기준으로 데이터를 조회하는 전통적인 방식  
  - (페이지 번호 – 1) × 페이지당 보여줄 개수만큼 건너뛰고, 그 다음 일정 개수를 가져옴  
- **장점**:  
  - 구현이 간단하고 직관적  
  - 특정 페이지 번호로 바로 이동하기가 쉬움  
- **단점**:  
  - 데이터가 많아질수록 높은 오프셋 구간에서는 성능이 급격히 떨어질 수 있음  
  - 검색/필터 결과가 동적으로 바뀌면, 누락·중복 문제가 발생할 수 있음 (예: 중간에 새로운 데이터가 추가되면 페이지 구성이 달라짐)
  - (“누락/중복 문제”: 페이지를 불러오는 중에 데이터가 추가/삭제되어, 사용자가 이미 본 데이터가 다시 보이거나, 새로 추가된 데이터가 이전 페이지에 있어야 하는데 다음 페이지에서 보이는 상황)

---

### 2. 커서 기반 페이지네이션
- **특징**:  
  - 각 데이터 행에 있는 고유 식별자(예: `id`, `created_at` 등)를 기준으로 “이 커서(이전 항목) 이후의 데이터”를 가져오는 방식  
  - 검색 시에도 정렬 기준(커서)만 잘 정의되면 안정적으로 다음 데이터를 찾을 수 있음  
- **장점**:  
  - 대규모 데이터에서 효율적이며, 중간에 레코드가 삽입·삭제되어도 누락이나 중복 문제가 상대적으로 적음  
  - “마지막으로 본 데이터 이후 데이터만” 조회하기 때문에, 페이지가 어긋나는 일이 덜함.
- **단점**:  
  - 구현 난이도가 오프셋 방식보다 높을 수 있음  
  - 정렬 기준을 미리 확정해야 하며, 여러 가지 정렬 기준을 동시에 다루기는 복잡함
  - (“정렬 기준”이란: 커서 기반 페이지네이션에서 커서가 되는 컬럼(예: `id`, `created_at`)을 지정해주는 행위)

---

### 3. 무한 스크롤/더 보기 버튼
- **특징**:  
  - 사용자가 스크롤을 내릴 때마다 또는 “더 보기” 버튼을 클릭할 때마다 일정 데이터량을 추가 로드  
  - SNS나 뉴스피드처럼 끊김 없이 데이터를 이어서 볼 수 있는 UI/UX  
- **장점**:  
  - 사용자 입장에서 연속적으로 데이터를 볼 수 있어 편리  
  - 화면 전환 없이 자연스럽게 더 많은 데이터를 불러올 수 있음  
- **단점**:  
  - 특정 위치(페이지)로 직접 접근하거나 공유하기가 어렵고, 검색 과정에서 “몇 번째 페이지”라는 개념이 불명확  
  - 스크롤 시점마다 서버 요청이 발생할 수 있으므로, 요청 관리와 퍼포먼스 최적화에 신경 써야 함  

---

## 우리 프로젝트에 적용할만한 페이지네이션 전략은?
- **검색(이름/기수) 기능와 함께 사용하기 좋으려면**:  
  - 일반적으로 **오프셋 기반 페이지네이션**이 구현이 쉽고, 검색 결과를 페이지 단위로 나누기에도 간편함.  
  - 데이터가 매우 많아질 것으로 예상되거나 성능 이슈가 우려된다면, **커서 기반 페이지네이션**을 고려해볼 수 있음.  
- **연속적·즉각적 로딩이 중요하고 특정 페이지로의 직접 이동이 크게 중요하지 않다면**:  
  - **무한 스크롤/더 보기 버튼**을 활용할 수도 있음.  
  - 다만, 검색 결과를 페이지 단위로 공유하거나 링크를 통해 바로 접근해야 한다면, 무한 스크롤 구현은 불편할 수 있음.

결론적으로, **오프셋 기반 페이지네이션**으로 시작하여 구현 단순성을 확보하고, 추후 데이터가 폭증(?)하여 성능 문제가 생길 때 **커서 기반으로 전환**하는 전략이 적합해 보입니다.

## 하지만 ...

현재 우리의 데이터 패칭 전략은 '한꺼번에 모든 데이터 불러오기'이기 때문에 데이터 패칭 전략이 먼저 바뀌지 않는 이상 페이지네이션 적용은 무의미함.

**Comment by DaleSeo** [comment]
- 오프셋 기반 페이지네이션으로 결정함
- @yolophg 님과 구체적인 페이지네이션 디자인 소통 필요
- 깃허브 페이지네이션 정책을 따르기
  - 필터링 조건이 바뀌면 페이지 초기화
  - 페이지네이션은 필터링된 데이터를 기준으로
