### ISSUE TITLE
디자인 업데이트 필요(색깔 접근성 문제 해결)

### ISSUE THREAD

**Issue by DaleSeo** [DaleStudy/leaderboard#163]
<img width="930" alt="Image" src="https://github.com/user-attachments/assets/5a5d273d-a315-4dcc-962a-b4da403b75cb" />

현재 버튼 색깔을 바꿔주니 대부분의 문제는 해결되었지만 확인해보니 table에 easy, medium hard들 text와 배경색의 대조도 부족해서 오류가 발생합니다. 이를 해결하기 위해 디자인 업데이트가 추가적으로 필요합니다.

**Comment by DaleSeo** [comment]
조치가 끝나면 https://github.com/DaleStudy/leaderboard/pull/162#discussion_r1898096258 에서 잠시 꺼둔 접근성 테스트를 활성화시켜주시기 바랍니다.

**Comment by yolophg** [comment]
최종적으로 easy/medium/hard color 색상이 각각 4.5:1 대조 ratio에 맞춰 아래와 같이 업데이트 되었으며, 피그마에도 업데이트 해두었으니 참고 부탁드립니다 :).
- easy: #007f71
- medium: #936a00
- hard: #e0284b

FYI: @DaleSeo @sounmind @Sunjae95 @SamTheKorean @HC-kang 

<img width="1107" alt="Image" src="https://github.com/user-attachments/assets/1000e20d-0d50-4f40-9e8c-7f1b8577948a" />
