### ISSUE TITLE
리더보드 페이지 디자인

### ISSUE THREAD

**Issue by DaleSeo** [DaleStudy/leaderboard#4]
기존 달레 스터디 웹사이트와 일관성이 있게 리더보드 페이지를 디자인해주세요.

![Image](https://github.com/user-attachments/assets/f64073a3-ff22-4c12-ae49-fc75b3c4ffce)

**Comment by DaleSeo** [comment]
등급
- 70 이상: 큰 나무
- 60 이상: 어린 나무
- 50 이상: 새싹
- X 이상: 씨앗

## 레퍼런스
![Image](https://github.com/user-attachments/assets/d018b961-a3d4-460c-9230-96f2b56d9c8a)

**Comment by yolophg** [comment]
**피그마 디자인 업데이트 :** 
@DaleSeo @sounmind @SamTheKorean @HC-kang @Sunjae95 

리더보드 페이지를 'growth'에 좀 더 초점을 두고 각 등급 아이콘들이 좀 더 부각되게 **등급 뱃지**를 디자인 해보았습니다.
적용되면 아래와 같은 모습입니다.

질문이나, 피드백 있으시면 피그마 댓글이나 여기로 언제든 남겨주시면 감사드리겠습니다!
![Screenshot 2024-10-31 at 01 07 26](https://github.com/user-attachments/assets/6f5b7c2c-b1b0-48b4-ae7c-5868df932c98)
![Screenshot 2024-10-31 at 01 02 18](https://github.com/user-attachments/assets/0e115f8c-1d44-4e86-8137-d2a1ed315943)

**Comment by DaleSeo** [comment]
@yolophg 님, 고생하셨어요! 이 정도면 저는 좋은 것 같아요 🤗 기존 메인 홈페이지 디자인이랑 결을 맞추시려고 노력하신 흔적이 보이네요! 피드백은 피그마에 남겼습니다.

**Comment by SamTheKorean** [comment]
너무 고생많으셨습니다! 색깔이나 포트들이 메인 사이트를 따라가고 있어서 참고하여 글로벌 스타일도 panda.config에 넣었습니다!

**Comment by sounmind** [comment]
와, 고생 많으셨습니다~!!! 디자인 넘 예쁜데요?

**Comment by Sunjae95** [comment]
와우.. 너무 고퀄인데요?! 너무 고생하셨습니다!
