### ISSUE TITLE
수료증 페이지 디자인

### ISSUE THREAD

**Issue by DaleSeo** [DaleStudy/leaderboard#5]
기존 달레 스터디 웹사이트와 일관성이 있게 수표즈 페이지를 디자인해주세요.

![Image](https://github.com/user-attachments/assets/b2623d68-779d-49c0-a891-4bec7081ba25)

**Comment by yolophg** [comment]
**피그마 디자인 업데이트 :**
@DaleSeo @sounmind @SamTheKorean @HC-kang @Sunjae95

수료증 페이지 디자인 완료되었습니다. 질문, 피드백 언제든지 환영입니다 :)
*마이너한 몇가지는 업데이트 될 예정입니다!(수료증 내용, 달레님 명칭 및 서명)
![Screenshot 2024-11-02 at 23 31 23](https://github.com/user-attachments/assets/a85014a8-5d89-45cb-9b41-d8c7fe067726)
