### ISSUE TITLE
Accessibility design 업데이트

### ISSUE THREAD

**Issue by yolophg** [DaleStudy/leaderboard#54]
@DaleSeo @SamTheKorean @sounmind @Sunjae95 @HC-kang 
기존 '달레 웹사이트' 기반인 Header에서 **focus는 없애고 focus-visible로 통일함**에 따라, 저희 리더보드 a11y도 figma에 전체적으로 업데이트 및 정리 되었으니 작업 시에 참고 부탁드립니다! 
자세한 히스토리는 아래 링크 쓰레드에서 확인하실 수 있습니다.
[관련 히스토리 링크](https://github.com/DaleStudy/leaderboard/pull/45#discussion_r1830318921)

<img width="706" alt="Screenshot 2024-11-06 at 22 15 36" src="https://github.com/user-attachments/assets/eaa20018-b8ea-446e-bc83-756448f31b60">

**Comment by DaleSeo** [comment]
다른 분들 피드백 없으시면 모임 때 `Done` 표시하면 될 것 같습니다.
