### ISSUE TITLE
API modules have duplicated code

### ISSUE THREAD

**Issue by sounmind** [DaleStudy/leaderboard#55]
현재 API 모듈에 중복 코드가 있습니다! 어떤 것을 사용하고, 어떤 것을 사용하지 않아야 할까요? 
예를 들어 Grade를 import 하려는 경우, 3개 파일이 나옵니다.
<img width="397" alt="image" src="https://github.com/user-attachments/assets/9b49b89e-14f0-4ef5-86f6-4e67c5788624">

- 관련 맥락
  - https://github.com/DaleStudy/leaderboard/pull/28#issuecomment-2461108691

**Comment by HC-kang** [comment]
외부에서 사용하실 타입들은 /api로 뽑아두었습니다.
`type.ts`와 `types.ts`는 마지막 네이밍 정리중에 실수했네요. 수정하겠습니다
