### ISSUE TITLE
Searchbar component

### ISSUE THREAD

**Issue by sounmind** [DaleStudy/leaderboard#57]
## Specification
(Searchbar에서 필터링을 한다는 것이 아님!)
- 기수 선택은 필수가 아니다.
- 텍스트 입력 후에 잠시 기다리면(0.2초) 검색한다.
- 기수 선택 시, 바로 검색을 한다.
- 텍스트가 공백이어도 기수 선택 시 검색을 한다.

**Comment by DaleSeo** [comment]
@sounmind Searchbar 컴포넌트를 수료증 페이지에 적용하는 부분은 본 티켓의 범위에서 벗어날까요? Top-down으로 개발을 하고 있기 때문에 저는 컴포넌트를 적용하는 것까지 범위로 보고 있었습니다.

**Comment by sounmind** [comment]
@DaleSeo 아, 제가 놓쳤네요. 말씀대로 실제로 페이지에서 컴포넌트를 불러오는 게 티켓의 범위라고 생각합니다.
