### ISSUE TITLE
"process is not defined" Error occurred

### ISSUE THREAD

**Issue by sounmind** [DaleStudy/leaderboard#60]
API 모듈 사용 시 해당 에러 발생.
브라우저 환경에서 process가 정의되지 않아서 발생하는 문제 같습니다.
https://vite.dev/guide/env-and-mode 를 참고해 해결하면 좋겠네요.

<img width="909" alt="image" src="https://github.com/user-attachments/assets/51dae064-f114-4808-b3b8-d88de4a8c30b">
<img width="609" alt="image" src="https://github.com/user-attachments/assets/ddc016ed-b800-4278-9488-ca3cfc235770">

**Comment by DaleSeo** [comment]
에궁... 이 부분에 대해서는 https://github.com/DaleStudy/leaderboard/pull/28#discussion_r1818159269 에서 말씀을 드렸는데 미처 조치가 되지 않았네요. Agile하게 프로젝트가 진행되려면 웹사이트는 항상 동작하는 상태가 되야하기 때문에 Top Priority로 해결해야할 것 같습니다.

**Comment by sounmind** [comment]
> 에궁... 이 부분에 대해서는 저도 우려가 되어 [#28 (comment)](https://github.com/DaleStudy/leaderboard/pull/28#discussion_r1818159269) 에서 코멘트를 남겼는데 미처 조치가 되지 않았네요. Agile하게 프로젝트가 진행되려면 웹사이트는 항상 동작하는 상태가 되야하기 때문에 Top Priority로 해결해야할 것 같습니다.

엄밀하게 말하면 현재 릴리즈 버전에서 해당 API 모듈을 사용하는 부분이 없어서 웹사이트가 돌아가지 않는(깨진) 상태는 아닙니다!
