### ISSUE TITLE
UI Design for Loading and Error States

### ISSUE THREAD

**Issue by yolophg** [DaleStudy/leaderboard#61]
- 페이지 없음과 일반 오류에 대한 목업 따로 필요
- 일반 오류 목업에는 저장소의 이슈 링크를 포함

**Comment by yolophg** [comment]
FYI : @DaleSeo @SamTheKorean @Sunjae95 @sounmind @HC-kang 

아래와 같이 loading/error(404, general) states 디자인을 완료하였습니다. 추가 피드백이나 건의사항이 있으시면 언제든 피그마에 남겨주세요!
작업시에는 Components를 참고하여 디테일한 사항을 확인해주시면 감사드리겠습니다.
**Loading)**
<img width="344" alt="Screenshot 2024-11-28 at 02 35 16" src="https://github.com/user-attachments/assets/e4cef09c-4911-4c07-8e3c-ff03aad2c842">
**Error-페이지 없음)**
<img width="600" alt="Screenshot 2024-11-28 at 02 42 24" src="https://github.com/user-attachments/assets/b63a7a14-d752-45c9-b61e-a32691b19dbb">
**Error-일반 오류)**
<img width="598" alt="Screenshot 2024-11-28 at 02 42 40" src="https://github.com/user-attachments/assets/0088b783-5a07-40b7-a349-bd1f76e2df6b">

**Comment by DaleSeo** [comment]
@yolophg LGTM 입니다! 수고하셨어용!
