### ISSUE TITLE
[spike] 기수 별 스터디 참여자를 어떻게 구할 수 있을까?

### ISSUE THREAD

**Issue by DaleSeo** [DaleStudy/leaderboard#7]
@Sunjae95 님께서 리더보드 페이지에서 기수 별로 스터디 참여자를 구분할 수 있으면 좋을 것 같다는 의견을 주셨는데요. 이미 만들어놓은 GitHub 팀을 활용하면 기수 별로 스터디 참여자의 목록을 구해낼 수 있을 것 같습니다.
 
- 1기: https://github.com/orgs/DaleStudy/teams/leetcode01
- 2기: https://github.com/orgs/DaleStudy/teams/leetcode

본 티켓을 통해서 기수 별로 스터디 참여자를 어떻게 구할 수 있는지 조사해봤으면 합니다. 구현 방법에 대해서 나중에 구현하시는 분이 참고할 수 있도록 정리해주세요.

**Comment by Sunjae95** [comment]
## Teams 구조

```
https://github.com/orgs/DaleStudy/teams
├─ coach
├─ leetcode
├─ leetcode01
├─ ..
└─ 새로운 팀
   ├─ https://github.com/orgs/DaleStudy/teams/leaderboard/teams
   ├─ 1기
   ├─ 2기
   ├─ 3기
   ├─ .. 
   └─ N기
```

## API reference

### 기수 가져오기

https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#list-child-teams

```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
 https://api.github.com/orgs/DaleStudy/teams/<새로운 팀>/teams
```

### 각 기수의 멤버 가져오기

https://docs.github.com/en/rest/teams/members?apiVersion=2022-11-28#list-team-members

```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/orgs/ORG/teams/<새로운 팀 내부의 팀 이름>/members
```

**Comment by Sunjae95** [comment]
기수를 분리하는 방법중 두가지정도 고민했어요. 
1. Pull Request시 label에 기수를 표기하여 API를 받을 때 label filter를 적용
2. teams에서 user의 id를 조회 및 PR 정보와 mapping

현재 organization에서 각 PR을 수정하는 것보단 teams를 수정하는것이 비용이 덜 들고 teams 관리가 가능하기 때문에 관리자 사용측면에서 유리하다고 판단하여 2번째 방법으로 조사했습니다.

### 다음은 이해를 돕기위한 시각화입니다.
![image](https://github.com/user-attachments/assets/68c3fe6a-01c0-4866-a211-d745628e2f60)

### 현재 예시이미지에서는 test만 존재하지만 실제 DaleStudy에서는 Teams 구조의 1depths와 유사하다고 이해하시면 됩니다.

![스크린샷 2024-10-13 오전 1 04 54](https://github.com/user-attachments/assets/c0a246ea-b857-4b7e-8723-c978990ab6de)

teams의 구조를 2depths 구조로 나뉘어 이름 컨벤션만 맞춰서 사용하게 되면 각 기수별로 나누는것이 가능하다고 생각합니다.
그리고 각 기수를 나누면 해당 기수의 멤버를 가져오는 API를 통해 각 user의 id를 뽑을 수 있어서 이를 토대로 구현하면 됩니다.

**Comment by DaleSeo** [comment]
@DaleSeo 의견: 
- 가급적 팀 구조를 flat하게 가져가면 좋을 것 같음
- 다른 부모 아래에 자식 팀의 이름이 허용되지 않는다면 굳이 팀 구조를 복잡하게 가져는 의미가 있을까?
- `https://api.github.com/orgs/DaleStudy/teams/<새로운 팀>/teams`가 팀 이름으로 필터링을 제공한다면 네이밍 컨벤션만 지켜줘도 가능할 것 같음 (ex. ?name=leetcode)

**Comment by DaleSeo** [comment]
@Sunjae95 API 문서를 보니 팀 이름으로 필터링은 안 되는 것 같은데요?
https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#list-teams

**Comment by DaleSeo** [comment]
결론: 팀 구조는 flat하게 유지하고, 대신 team 모두 불러와서, leetcode로 시작하는 팀에 대해서만 멤버 불러오기
