### ISSUE TITLE
Obfuscate Exposed Tokens

### ISSUE THREAD

**Issue by HC-kang** [DaleStudy/leaderboard#73]
피치못하게 공개되는 Github API Key의 직접적인 노출을 막기 위한 토큰 난독화 처리입니다.

**Comment by HC-kang** [comment]
여러 방면으로 고민해보았는데,

1. 코드가 퍼블릭 레포로 공개된다.
2. 요청 자체가 브라우저를 통해 이루어진다.

이 두 전제 하에서는 정말 토큰을 조금이라도 가릴 방법이 없고, 추후 토큰관리에 부담만 생길 것 같네요.
단순히 base64등으로 인코딩해서 스크래퍼에 의한 API 키 수집만 막는게 최선인 것 같습니다.

**Comment by DaleSeo** [comment]
> 피치못하게 공개되는 Github API Key의 직접적인 노출을 막기 위한 토큰 난독화 처리입니다.

@HC-kang 님, 이 티켓의 목적이 위와 같다면 토큰 난독화 처리에 대한 코드가 추가되야 하지 않나요? 아래 코멘트에도 난독화하는 방법 밖에는 없다라고 다시 한 번 결론을 내리신 것 같은데 티켓을 왜 그냥 닫으셨는지 모르겠습니다.

**Comment by DaleSeo** [comment]
어차피 Network 탭 보면 토큰이 보이기 때문에 큰 쓸모 없음. #14 에서 다시 고려해봤으면 좋겠음.
