### ISSUE TITLE
Spring 9 미팅

### ISSUE THREAD

**Issue by DaleSeo** [DaleStudy/leaderboard#95]
Where are you Dale...?

## Progress
- 지난 미팅 리뷰 #75
- 지난 Sprint 리뷰 with 데모
- 다음 Sprint 계획
- **이번 주의 챌린지들 공유**

## Agenda
- @DaleSeo Chromatic 사용법 교육, Chromatic 협업 프로세스 논의
- 리트코드 스터디 재수 시, 어떻게 제출 여부를 취급할 것인가? @sounmind #100 
- 페이지네이션 추가하기로 결정. 얼마나 시간이 걸릴지는 이 Spike가 끝나고 합의

## Action Items
- [x] Chromatic 댓글이나 리뷰 알림을 디스코드에 연동할 수 있는지 알아보기 #110
- [ ] 회고 작성하기!

## Retro
https://github.com/DaleStudy/leaderboard/discussions/93

**Comment by sounmind** [comment]
교육이라니. 기대됩니다ㅎㅎ
